"""add card timestamp

Revision ID: 6823241e5b6a
Revises: 56cc60ecf090
Create Date: 2022-06-09 23:09:29.077147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6823241e5b6a'
down_revision = '56cc60ecf090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informative_card', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informative_card', 'created_at')
    # ### end Alembic commands ###
